Disable delete collections for KUZZLE V1
kuzzleio/kuzzle-admin-console pull request #807
Opened 2020-08-19 13:51 UTC by morgandruesne

## What does this PR do ?
Disable the possibility in the UI to delete collections with an environment for kuzzle v1

2020-08-19 15:18 UTC, xbill82 requested changes
Getter is better 😎

2020-08-19 15:18 UTC, xbill82 commented on src/components/Data/Collections/CollectionList.vue
> +                  @click="deleteCollections"
```suggestion
                  v-if="
                    $store.getters.kuzzle.currentEnvironment.backendMajorVersion !== 1
                  "
                  @click="deleteCollections"
```

2020-08-19 15:18 UTC, xbill82 commented on src/components/Data/Collections/CollectionList.vue
> +                $store.state.kuzzle.environments[$store.state.kuzzle.currentId]
```suggestion
                $store.getters.kuzzle.currentEnvironment
```

2020-08-19 15:18 UTC, xbill82 commented on src/components/Data/Collections/CollectionList.vue
> +            $store.state.kuzzle.environments[$store.state.kuzzle.currentId]
```suggestion
            $store.getters.kuzzle.currentEnvironment
```

2020-08-20 09:01 UTC, xbill82 approved these changes

2020-08-20 09:02 UTC, xbill82 requested changes
Could you add an e2e test, please?

2020-08-25 12:31 UTC, berthieresteban approved these changes

2020-09-02 14:12 UTC, Njuelle approved these changes

2020-09-02 15:51 UTC, xbill82 approved these changes

2020-09-02 15:51 UTC, merged