Fix re authentificate when token expire
kuzzleio/kuzzle-admin-console pull request #813
Opened 2020-08-26 13:19 UTC by morgandruesne

## What does this PR do ?
Change the e.id to allow the user to re-authenticate after the token has expired

2020-08-27 07:22 UTC, xbill82 approved these changes

2020-08-27 07:22 UTC, xbill82 commented on src/components/Home.vue
> +      console.log("plop");
```suggestion

```

2020-09-02 13:58 UTC, Njuelle requested changes

2020-09-02 13:58 UTC, Njuelle commented on test/e2e/cypress/integration/single-backend/login.spec.js
> +  it.only('Should be able to login without losing context when token expires', () => {
```suggestion
  it('Should be able to login without losing context when token expires', () => {
```

2020-09-02 14:01 UTC, Njuelle approved these changes

2020-09-02 14:05 UTC, merged