Add form-view for create / edit documents
kuzzleio/kuzzle-admin-console pull request #840
Opened 2020-11-05 12:54 UTC by Njuelle

## What does this PR do ?

### How should this be manually tested?

  - Step 1 :
  - Step 2 :
  - Step 3 :  
  ...

### Other changes

### Boyscout

### Screenshots (if appropriate)

2020-11-10 16:42 UTC, jenow reviewed
When I have a nested object, it shows me a textare with just `{}` inside. It would be good to at least have the mapping. 
![a](https://user-images.githubusercontent.com/592088/98703702-0fa01b80-237c-11eb-8134-3ed0d7478df9.png)

2020-11-12 11:03 UTC, alexandrebouthinon approved these changes

2020-11-13 09:40 UTC, berthieresteban commented
Just a question
Since dates are timestamp, shouldn't we allow user to enter date and hour by adding a `<b-timepicker>` for example ? 
![image](https://user-images.githubusercontent.com/44427849/99057592-4ce2f400-259c-11eb-967e-22dc3090c037.png)

2020-11-13 09:49 UTC, berthieresteban approved these changes

2020-11-13 14:49 UTC, berthieresteban requested changes

2020-11-13 14:49 UTC, berthieresteban commented on src/services/formSchema.ts
> +  date: 'date'
```suggestion
  date: 'datetime-local'
```

2020-11-13 16:02 UTC, xbill82 reviewed
All good so far, let's wait for the date improvement next week. I'll change this to a WIP PR.

2020-11-17 11:09 UTC, Njuelle commented
DateTime form input :
![image](https://user-images.githubusercontent.com/3192870/99383069-aa917c00-28cd-11eb-851f-1df80f6a2628.png)

2020-11-17 11:17 UTC, Njuelle commented
Json input form with mapping :
![image](https://user-images.githubusercontent.com/3192870/99383849-c77a7f00-28ce-11eb-8ebb-2e2759dfdfb0.png)

2020-11-20 15:28 UTC, berthieresteban commented
Ci tests fails only on the date/time pickers of the form view, we are asserting timestamps and there is a time difference of 1h.
It might be because of the runners timezone.

2020-11-23 16:08 UTC, alexandrebouthinon requested changes

2020-11-23 16:09 UTC, jenow approved these changes

2020-11-23 16:15 UTC, alexandrebouthinon approved these changes

2020-11-23 16:16 UTC, merged