fix bug delete history search
kuzzleio/kuzzle-admin-console pull request #924
Opened 2021-06-04 14:06 UTC by berthieresteban

fix #877

2021-06-07 12:48 UTC, xbill82 approved these changes

2021-06-08 16:02 UTC, Njuelle requested changes

2021-06-08 16:02 UTC, Njuelle commented on src/components/Common/Filters/FilterHistoryItem.vue
> +              :data-cy="'FilterHistoryItem-deleteBtn--' + id"
```suggestion
              :data-cy="`FilterHistoryItem-deleteBtn--${id}`"
```

2021-06-08 16:02 UTC, Njuelle commented on test/e2e/cypress/integration/single-backend/search.spec.js
> +  it.only('Should be able to delete a previous searche in the search history.', () => {
```suggestion
  it('Should be able to delete a previous search in the search history', () => {
```

2021-06-09 08:30 UTC, berthieresteban commented on test/e2e/cypress/integration/single-backend/search.spec.js
> +  it.only('Should be able to delete a previous searche in the search history.', () => {
Damn, you figured it out

2021-06-11 13:36 UTC, Njuelle approved these changes

2021-06-11 13:37 UTC, merged