Delete index dropdown
kuzzleio/kuzzle-admin-console pull request #950
Opened 2021-07-12 14:43 UTC by berthieresteban

fix #735 

add actions dropdown on index view (collection list) to allow delete index 
![acdeleteindex](https://user-images.githubusercontent.com/44427849/125307279-35792800-e330-11eb-937e-afcc6516e797.gif)

2021-07-15 10:30 UTC, xbill82 requested changes
Good job! Just a few nitpicking!

2021-07-15 10:30 UTC, xbill82 commented on src/components/Data/Indexes/DropdownActions.vue
> +        $store.direct.getters.kuzzle.currentEnvironment.backendMajorVersion !==
please map this to a computed :)

2021-07-15 10:30 UTC, xbill82 commented on src/components/Data/Indexes/DropdownActions.vue
> +            $store.direct.getters.kuzzle.currentEnvironment
same same

2021-07-21 13:53 UTC, berthieresteban commented on src/components/Data/Indexes/DeleteIndexModal.vue
> +      <strong>{{ truncateName(index ? index.name : '') }}</strong> deletion
`truncateName` is generic and is used in a lot of views for various names.
In `truncateName` the `name === null` state is already handled
Here I just test that `index` is empty so I'm sure to be able to read `index.name` which is different that if `index.name === null`

Not sure if I'm clear...

2021-08-05 13:22 UTC, xbill82 approved these changes

2021-08-12 09:27 UTC, alexandrebouthinon approved these changes

2021-08-12 09:27 UTC, merged