Modify dynamic mapping selection for creation and update
kuzzleio/kuzzle-admin-console pull request #961
Opened 2021-07-29 12:47 UTC by jsatge

## What does this PR do ?

fixes #884

Delete radio buttons for dynamic mapping and add pre-filled JSON, with a global "dynamic:" false property by default.

2021-07-30 12:18 UTC, berthieresteban requested changes

2021-07-30 12:18 UTC, berthieresteban commented on src/components/Data/Collections/Update.vue
> +      return { dynamic: dynamic, properties: mapping }
It seems not possible to get `mapping.dynamic` after omit `dynamic` 
Also, `mapping.dynamic` will lead to an error if `this.collection` is null

2021-07-30 12:18 UTC, berthieresteban commented on src/vuex/modules/index/store.ts
>      })
can replace `{ ...mapping }` by `mapping`

2021-07-30 12:18 UTC, berthieresteban commented on src/vuex/modules/index/store.ts
>        }
same here

2021-07-30 12:18 UTC, berthieresteban commented on test/e2e/cypress/integration/single-backend/collections.spec.js
> +        {
```suggestion
"dynamic": false,
"properties": {
```

2021-11-05 13:53 UTC, xbill82 approved these changes

2021-11-16 14:58 UTC, rolljee approved these changes

2021-11-16 15:51 UTC, merged