Use Kepler to retrieve product usage metrics
kuzzleio/kuzzle-admin-console pull request #987
Opened 2022-02-21 11:27 UTC by alexandrebouthinon

## What does this PR do ?

As we done on Kourou, let's use it on the Admin Console

## ToDo 
- [x] Integrate Kepler Companion in the Admin Console
- [ ] Make a "cookie banner" to permit users to disable it
- [ ] Add current environment name `console.kuzzle.io` or `next-console.kuzzle.io`

2022-02-21 12:39 UTC, Aschen commented on src/main.ts
> +  await analytics.track({
You should not await here but only empty catch to not degrade the UX

2022-02-21 17:19 UTC, Aschen approved these changes

2022-02-23 06:52 UTC, Aschen requested changes

2022-02-23 06:52 UTC, Aschen commented on src/routes/index.ts
> +      await analytics.add({
Can you add a catch to this promise so it never prints error to the console?

2022-02-23 09:38 UTC, Njuelle approved these changes

2022-02-23 09:45 UTC, Njuelle commented
the tests fail because the new banner covers elements of the DOM and prevents the click on these elements. IMHO the best way to fix this would be to disable the banner and the telemetry during the tests

2022-02-23 14:13 UTC, Aschen approved these changes

2022-02-23 14:14 UTC, Aschen commented
LGTM :+1:

2022-02-23 14:34 UTC, merged